version: "3.8"
services:
  app:
    build:
      context: .
    container_name: fastapi_test_app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    command: ["make", "run"]

  db:
    image: neo4j
    container_name: neo4j_db
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
